---
title: "Script1"
output: html_document
---

#
# This is a script to create a table of taxonomic regrouping
#
# 1. Setup ----
#--------------------------------------------------------------------------#
```{r}
library('data.tree')
library('readr')
library('tidyverse')
library('readxl')
library('vroom')
library(dplyr)
```
# 2. Open ecotaxa table ----
#--------------------------------------------------------------------------#
#  data
```{r}
ecotaxa300m <- read_tsv("../Input/ecotaxa_export_300m.tsv")
```
# only keep the needed columns
```{r}
eco300m_reduced <- ecotaxa300m %>% 
  select(c("object_id", "taxon"= "object_annotation_category", "lineage" = "object_annotation_hierarchy","object_annotation_status"))
```
# replace the '>' with '/'
```{r}
eco300m_reduced$lineage <- gsub('>','/',eco300m_reduced$lineage)

write_csv(ecotaxa300m, "../Output/Intermediary Data/Ecotaxa300m.csv")
```
## 3. Build the tree ----
#--------------------------------------------------------------------------#
# count the combinations of obj per taxon, linage
```{r}
tc <- count(eco300m_reduced, taxon, lineage) %>% 
  rename(pathString=lineage) %>%   
  arrange(pathString) %>% 
  as.Node()

print(tc, "taxon","n", limit = 60)
```
# Convert to dataframe
```{r}
tcd <- ToDataFrameTree(tc, "taxon", "n")
```
# 4. Création du tableau avec tous les taxons 
```{r}
unique_taxa <- eco300m_reduced %>%
  distinct(taxon) %>%
  mutate(taxo_rough = NA)
```
# L’enregistrer pour le remplir à la main
```{r}
write_csv(unique_taxa, "../Output/Intermediary Data/table_taxons.tsv")
```

